In [29]:
import pandas as pd

In [30]:
df = pd.read_csv('Car Dataset Processed.csv')

In [31]:
df.columns

Index(['Unnamed: 0', 'car_name', 'registration_year', 'insurance_validity',
       'fuel_type', 'seats', 'kms_driven', 'ownsership', 'transmission',
       'manufacturing_year', 'mileage(kmpl)', 'engine(cc)', 'max_power(bhp)',
       'torque(Nm)', 'price(in lakhs)'],
      dtype='object')

In [32]:
df.head(2)

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs)
0,0,2017 Mercedes-Benz S-Class S400,Jul-17,Comprehensive,Petrol,5,56000,First Owner,Automatic,2017,7.81,2996.0,2996.0,333.0,63.75
1,1,2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI,Jan-21,Comprehensive,Petrol,5,30615,First Owner,Automatic,2020,17.40,999.0,999.0,9863.0,8.99

In [33]:
df['insurance_validity'].value_counts()

insurance_validity
Comprehensive            1081
Third Party insurance     289
Zero Dep                   64
Third Party                63
Not Available               2
Name: count, dtype: int64

In [34]:
df['insurance_validity'].map({'Comprehensive':0,'Third Party insurance':1,'Zero Dep':2,'Not Available':3,'Third Party':1})

0       0
1       0
2       0
3       0
4       0
       ..
1494    1
1495    0
1496    0
1497    0
1498    0
Name: insurance_validity, Length: 1499, dtype: int64

In [35]:
df['fuel_type'].value_counts()

fuel_type
Petrol    997
Diesel    480
CNG        22
Name: count, dtype: int64

In [36]:
df['fuel_type']=df['fuel_type'].map({'Petrol':0,'Diesel':1,'CNG':2})

In [37]:
df['ownsership'].value_counts()

ownsership
First Owner     1236
Second Owner     240
Third Owner       21
Fifth Owner        2
Name: count, dtype: int64

In [38]:
df['ownsership']=df['ownsership'].map({'First Owner':0,'Second Owner':1,'Third Owner ':2,'Fifth Owner':3})

In [39]:
df['transmission'].value_counts()

transmission
Manual       832
Automatic    667
Name: count, dtype: int64

In [40]:
df['transmission']=df['transmission'].map({'Manual':0,'Automatic':1})

In [41]:
df['transmission'].value_counts()

transmission
0    832
1    667
Name: count, dtype: int64

In [42]:
df['registration_year']

0       Jul-17
1       Jan-21
2       Sep-18
3       Dec-19
4       Aug-19
         ...
1494    May-22
1495    Aug-20
1496    Jun-17
1497    May-18
1498    May-18
Name: registration_year, Length: 1499, dtype: object

In [43]:
df['year'] = pd.to_datetime(df['registration_year'], format='mixed', errors='coerce').dt.year

In [44]:
df['registration_year'].value_counts()

registration_year
Jul-18    38
Jul-17    29
Aug-18    29
May-17    26
Oct-18    25
          ..
Feb-13     1
Nov-09     1
Apr-13     1
Nov-11     1
Sep-12     1
Name: count, Length: 175, dtype: int64

In [45]:
df['year'] = df['registration_year'].apply(
    lambda x: int(x) if str(x).isdigit() 
    else 2000 + int(x.split('-')[1])
)

In [46]:
df['registration_year'].unique()

array(['Jul-17', 'Jan-21', 'Sep-18', 'Dec-19', 'Aug-19', 'Feb-19',
       'Jul-18', 'Apr-15', 'Mar-19', 'Mar-20', 'Feb-22', '2014', 'Jan-22',
       'Apr-19', 'Aug-22', 'Mar-18', 'Nov-19', 'Nov-20', 'Sep-21',
       'Oct-10', 'Sep-15', 'Aug-11', 'Dec-15', 'Aug-17', 'Aug-20', '2018',
       'Oct-19', 'Dec-22', 'Jun-18', '2017', 'Jun-17', 'May-10', 'Mar-23',
       'Nov-15', 'Sep-20', 'Jul-21', 'Aug-18', 'Jun-20', 'Apr-21',
       'Nov-23', 'Dec-20', 'Jun-21', 'May-11', '2016', 'Oct-17', 'Nov-14',
       'Feb-18', '2009', 'Jul-16', 'Aug-21', 'Nov-18', 'Oct-18', 'Mar-17',
       'May-19', 'May-13', 'May-23', 'Jul-14', '2015', 'Sep-16', 'May-22',
       'Aug-15', 'Mar-21', 'Mar-22', 'Oct-20', 'Apr-16', 'Sep-23',
       'Dec-21', 'Nov-21', 'Dec-14', 'Jul-22', 'Jun-23', 'Jul-19',
       'Dec-12', 'Dec-16', 'Jun-16', 'Sep-19', 'Jun-10', 'Oct-14',
       'Mar-16', 'Jun-11', 'Dec-18', 'Feb-20', 'Apr-20', 'Jan-11',
       'Oct-15', 'Jan-19', 'Jul-13', 'May-21', 'Aug-13', 'Oct-13',
       'Nov-17', 'May-17', 'Jan-20', 'May-15', 'Sep-17', 'Apr-22',
       'Nov-12', 'Sep-14', '2011', 'Aug-16', '2020', '2021', 'Nov-13',
       'Nov-16', 'Mar-11', 'Jan-14', 'Sep-13', '2012', 'Jun-19', 'May-14',
       'Jun-14', 'Mar-14', 'Oct-22', 'May-12', 'Mar-15', 'May-16',
       'Oct-16', 'Jan-23', 'Jan-16', '2023', 'Jun-15', 'Feb-13', 'Apr-23',
       'Jul-15', 'Nov-22', 'Feb-12', 'Feb-23', 'Jul-20', '2013', 'Mar-13',
       'Jan-12', 'Aug-23', 'Mar-12', 'Feb-16', 'Jan-15', 'Apr-18',
       'May-18', 'Feb-15', 'Apr-13', 'Dec-17', 'Aug-14', '2019', 'Jan-17',
       'Jul-23', 'Oct-21', 'Apr-17', 'Jul-12', 'Feb-17', 'Mar-09',
       'Jul-10', 'Jun-22', 'Jun-12', 'Nov-11', 'Nov-10', 'Apr-12',
       'Jan-18', 'Nov-09', 'Jun-13', '2010', 'Sep-22', 'Oct-12', 'Apr-11',
       'Sep-12', '2007', 'Apr-14', 'Aug-10', 'May-09', 'Jan-09', 'Feb-21',
       'Sep-11', 'Dec-09', 'Dec-13', 'Mar-10', 'Jan-10', '2022'],
      dtype=object)

In [47]:
df['year'] = pd.to_datetime(
    df['registration_year'], 
    format='mixed', 
    errors='coerce'
).dt.year

In [48]:
df[['registration_year','year']].head(10)

  registration_year  year
0            Jul-17   NaN
1            Jan-21   NaN
2            Sep-18   NaN
3            Dec-19   NaN
4            Aug-19   NaN
5            Jul-17   NaN
6            Feb-19   NaN
7            Jul-18   NaN
8            Apr-15   NaN
9            Mar-19   NaN

In [49]:
def extract_year(x):
    x = str(x).strip()
    
    # Case 1: already full year (e.g., 2014)
    if x.isdigit():
        return int(x)
    
    # Case 2: format like "Jul-17"
    else:
        year = int(x.split('-')[1])
        
        # convert 2-digit → 4-digit
        if year <= 25:   # adjust threshold if needed
            return 2000 + year
        else:
            return 1900 + year

df['year'] = df['registration_year'].apply(extract_year)

In [50]:
current_year = 2026
df['car_age'] = current_year - df['year']

In [51]:
df['car_age'].value_counts()

car_age
8     233
9     189
7     181
10    136
11    131
6     126
5     109
4     100
12    100
14     51
13     47
3      44
15     23
16     17
17     11
19      1
Name: count, dtype: int64

In [52]:
df['car_age'].value_counts().sort_index()

car_age
3      44
4     100
5     109
6     126
7     181
8     233
9     189
10    136
11    131
12    100
13     47
14     51
15     23
16     17
17     11
19      1
Name: count, dtype: int64

In [54]:
X = df[['insurance_validity','fuel_type','kms_driven','ownsership','transmission']]
y = df['price(in lakhs)']

In [55]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR

In [75]:
import pandas as pd

test = pd.DataFrame([{
    'insurance_validity': insurance_validity,
    'fuel_type': fuel_type,
    'kms_driven': kms_driven,
    'ownsership': ownsership,
    'transmission': transmission
}])

In [76]:
test = pd.get_dummies(test)

In [77]:
test = test.reindex(columns=X.columns, fill_value=0)

In [78]:
yp = int(final_model.predict(test)[0])
print('Predicted Car Price is {} Rs.'.format(yp))

Predicted Car Price is 11 Rs.

In [66]:
print(X.isna().sum())

fuel_type                                    0
kms_driven                                   0
ownsership                                  21
transmission                                 0
insurance_validity_Comprehensive             0
insurance_validity_Not Available             0
insurance_validity_Third Party               0
insurance_validity_Third Party insurance     0
insurance_validity_Zero Dep                  0
dtype: int64

In [67]:
X['ownsership'] = X['ownsership'].fillna('Unknown')

In [70]:
from sklearn.metrics import r2_score

for name, model in models.items():
    model.fit(X, y)
    y_pred = model.predict(X)
    sc = r2_score(y, y_pred)
    print(name, "R2 Score:", sc)

LinReg R2 Score: 0.029261441034430513
KNN-3 R2 Score: 0.5927589743194316
SVM-Poly R2 Score: -0.0021593409673368313

In [71]:
d1={'Comprehensive': 0,'Third Party insurance': 1,'Zero Dep': 2,'Not Available': 3,'Third Party': 1}
d2={'Petrol': 0, 'Diesel': 1, 'CNG': 2}
d3={'Manual': 0, 'Automatic': 1}
d4={'First Owner': 1,'Second Owner': 2,'Third Owner': 3,'Fifth Owner': 5,'Fourth Owner': 4}

In [79]:
final_model = models['KNN-3']

In [82]:
import pickle 
pickle.dump(final_model,open('final_model.pkl','wb'))

In [81]:
import pickle

pickle.dump(X.columns, open('columns.pkl', 'wb'))
pickle.dump(final_model, open('model.pkl', 'wb'))